- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: ansible-cloudnow@cloudnow-labs.iam.gserviceaccount.com
    credentials_file: /etc/ansible/cloudnow-labs-8feab535e6dc.json
    project_id: cloudnow-labs
    machine_type: g1-small
    image: debian-8

  tasks:

   - name: Launch instances
     gce:
         instance_names: ans-test
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
