- hosts: "swarm-managers:swarm-nodes"
  gather_facts: True
  connection: local
  vars:
    region: "us-west-2"
  tasks:
    - include_vars: "~/.aws/aws_config.yml"
    - ec2_remote_facts:
               region : "{{ region }}"
               aws_access_key: "{{ aws_access_key }}"
               aws_secret_key: "{{ aws_secret_key }}"
               filters:
                  private_ip_address: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
      register: ec2_info
    - debug: var=ec2_info
    - ec2: 
           state='absent'
           region="{{ region }}"
           instance_ids="{{ item }}"
           aws_access_key="{{ aws_access_key }}"
           aws_secret_key="{{ aws_secret_key }}"
           wait=true
      with_items: "{{ ec2_info.instances[0].id }}"
